//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstado
    {
        public int est_Id { get; set; }
        public string est_Descripcion { get; set; }
        public int est_UsuarioCrea { get; set; }
        public System.DateTime est_FechaCrea { get; set; }
        public Nullable<int> est_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> est_FechaModifica { get; set; }
    }
}
