//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbParametro1
    {
        public byte par_Id { get; set; }
        public string par_NombreEmpresa { get; set; }
        public string par_TelefonoEmpresa { get; set; }
        public string par_CorreoEmpresa { get; set; }
        public string par_Emisor { get; set; }
        public string par_Password { get; set; }
        public string par_Mensaje { get; set; }
        public string par_Asunto { get; set; }
        public string par_Destinatario { get; set; }
        public string par_Servidor { get; set; }
        public int par_Puerto { get; set; }
        public string par_PathLogo { get; set; }
    }
}
