//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProducto
    {
        public int pro_Id { get; set; }
        public string pro_Descripcion { get; set; }
        public int pro_UsuarioCrea { get; set; }
        public System.DateTime pro_FechaCrea { get; set; }
        public Nullable<int> pro_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> pro_FechaModifica { get; set; }
    }
}
