//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoSolicitud
    {
        public int tipsol_Id { get; set; }
        public string tipsol_Descripcion { get; set; }
        public int tipsol_UsuarioCrea { get; set; }
        public System.DateTime tipsol_FechaCrea { get; set; }
        public Nullable<int> tipsol_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tipsol_FechaModifica { get; set; }
    }
}
