//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoViatico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTipoViatico()
        {
            this.tbHistorialdeSolicitud = new HashSet<tbHistorialdeSolicitud>();
            this.tbSolicitud = new HashSet<tbSolicitud>();
        }
    
        public int tpv_Id { get; set; }
        public string tpv_Descripcion { get; set; }
        public int tpv_UsuarioCrea { get; set; }
        public System.DateTime tpv_FechaCrea { get; set; }
        public Nullable<int> tpv_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tpv_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHistorialdeSolicitud> tbHistorialdeSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSolicitud> tbSolicitud { get; set; }
    }
}
