//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGEM_BIDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUnidadMedida
    {
        public int uni_Id { get; set; }
        public string uni_Descripcion { get; set; }
        public string uni_Abreviatura { get; set; }
        public int uni_UsuarioCrea { get; set; }
        public System.DateTime uni_FechaCrea { get; set; }
        public Nullable<int> uni_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> uni_FechaModifica { get; set; }
    }
}
